### ISSUE TITLE
Unable to find release page for None

### ISSUE THREAD

**Issue by jerryturcios08** [denoland/deno_install#15]
Whenever I try to run
```
curl -L https://deno.land/x/install/install.py | python
```
I get the following along with the executable not appearing under ~/.deno/bin/
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3089  100  3089    0     0   8423      0 --:--:-- --:--:-- --:--:-- 45426
Unable to find release page for None
```
I am on a Mac running version 10.14.1

**Comment by ry** [comment]
I'm unable to repeat the failure. Further debugging would be helpful.

(And you can always download the binary manually at https://github.com/denoland/deno/releases - note that the gzip file contains only the executable binary which will have to be made executable with chmod.)

**Comment by jerryturcios08** [comment]
Thanks for the response, I was able to use the binary you linked. I will look further into the issue I have been running into when running the curl command when I get the chance. @ry

**Comment by hayd** [comment]
Most likely this is an intermittent http error on GitHub, we could retry the URL several times. We could also throw the error rather than hide it.

https://github.com/denoland/deno_install/blob/b6b938f7446b2656f59f6526deb35fe87bbf3f84/install.py#L42-L46

**Comment by alexkuz** [comment]
@hayd I also ran into this - here's what I've got from exception:
```
<urlopen error [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
```
After upgrading python from 2.7.6 to latest version (2.7.15) I've got this:
```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
```
Then I installed certificates with `Install Certificates.command` (as was suggested in ReadMe) and finally it worked.
Hope it helps :)

**Comment by hayd** [comment]
Yikes. I guess 2.7.6 is from 2013 so it's good to update.

```diff
  try: 
      html = urlopen(url).read().decode('utf-8') 
- except: 
+ except HTTPError as e:  # Note: HTTPError needs to be imported
+    print(e)
     print("Unable to find release page for", tag)
     sys.exit(1) 
```
Would at least show it's a protocol issue and perhaps be searchable to this issue.

**Comment by alexkuz** [comment]
BTW it's probably better to catch URLError instead of HTTPError - I'm not sure if these errors were of HTTPError type.

**Comment by MarkTiedemann** [comment]
Since #42, the python installer is deprecated. So this issue can be closed.

cc @ry
